version: "3.9"

services:
  vue-app:
    build: .
    container_name: vue-app
    ports:
    - "8080:8080"
    volumes:
    - .:/app
    - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run dev"

  volumes:
  node_modules:
